import {mentor,Sudeep,Siddhi,Shubham,Roshan,Rohit,Arya,Aditya,Javed,Ayush,Arnav,} from "../assets"
const Mentors2023 = [
  {
    name: "Sudeep Ranjan Sahoo",
    designation: "Mentor",
    image: Sudeep,
    github: "https://github.com/srs-sudeep",
    linkedln: "https://www.linkedin.com/in/sudeep-ranjan-sahoo-b82355232/",
  },
  {
    name: "Aditya Dubey",
    designation: "Mentor",
    image:  Aditya,
    github: "www.github.com",
    linkedln: "www.linkedln.com",
  },
  {
    name: "Arya Lanjewar",
    designation: "Mentor",
    image:  Arya,
    github: "www.github.com/AryaLanjewar3005",
    linkedln: "www.linkedln.com/in/lanjewar-arya",
  },
  {
    name: "Ayush Krishnan",
    designation: "Mentor",
    image:  Ayush,
    github: "www.github.com",
    linkedln: "www.linkedln.com",
  },
  {
    name: "Javed Habib",
    designation: "Mentor",
    image:  Javed,
    github: "www.github.com",
    linkedln: "www.linkedln.com",
  },
  {
    name: "Roshan Jha",
    designation: "Mentor",
    image:  Roshan,
    github: "www.github.com",
    linkedln: "www.linkedln.com",
  },
  {
    name: "Rohit Ashwani",
    designation: "Mentor",
    image:  Rohit,
    github: "https://github.com/rohitashwani1",
    linkedln: "https://www.linkedin.com/in/rohit-ashwani-25654a248/",
  },
  {
    name: "Shubham Daule",
    designation: "Mentor",
    image:  Shubham,
    github: "www.github.com",
    linkedln: "www.linkedln.com",
  },
  {
    name: "Siddhi Aggarwal",
    designation: "Mentor",
    image:  Siddhi,
    github: "www.github.com",
    linkedln: "www.linkedln.com",
  },
  {
    name: "Arnav Prakash Choudhury",
    designation: "Mentor",
    image:  Arnav,
    github: "www.github.com",
    linkedln: "www.linkedln.com",
  },
  
  
];
const Mentors2022 = [
  {
    name: "Aakash Thatte",
    designation: "Mentor",
    image: mentor,
    github: "www.github.com",
    linkedln: "www.linkedln.com",
  },
  {
    name: "Abhishek Singh Khushwaha",
    designation: "Mentor",
    image:  mentor,
    github: "www.github.com",
    linkedln: "www.linkedln.com",
  },
  {
    name: "Ananya Hooda",
    designation: "Mentor",
    image:  mentor,
    github: "www.github.com",
    linkedln: "www.linkedln.com",
  },
  {
    name: "Anshu Kumar",
    designation: "Mentor",
    image:  mentor,
    github: "www.github.com",
    linkedln: "www.linkedln.com",
  },
  {
    name: "Sudeep Ranjan Sahoo",
    designation: "Mentor",
    image:  mentor,
    github: "www.github.com",
    linkedln: "www.linkedln.com",
  },
  {
    name: "Chaitanya Bisht",
    designation: "Mentor",
    image:  mentor,
    github: "www.github.com",
    linkedln: "www.linkedln.com",
  },
  {
    name: "Harshith Naresh Chunduri",
    designation: "Mentor",
    image:  mentor,
    github: "www.github.com",
    linkedln: "www.linkedln.com",
  },
  {
    name: "Madhur Jain",
    designation: "Mentor",
    image:  mentor,
    github: "www.github.com",
    linkedln: "www.linkedln.com",
  },
  {
    name: "Sarvesh Kumar",
    designation: "Mentor",
    image:  mentor,
    github: "www.github.com",
    linkedln: "www.linkedln.com",
  },
];
const Mentors2021 = [
  {
    name: "Ambar",
    designation: "Mentor",
    image: mentor,
    github: "www.github.com",
    linkedln: "www.linkedln.com",
  },
  {
    name: "Shikhar",
    designation: "Mentor",
    image:  mentor,
    github: "www.github.com",
    linkedln: "www.linkedln.com",
  },
  {
    name: "Rishi",
    designation: "Mentor",
    image:  mentor,
    github: "www.github.com",
    linkedln: "www.linkedln.com",
  },
  {
    name: "Shashwat",
    designation: "Mentor",
    image:  mentor,
    github: "www.github.com",
    linkedln: "www.linkedln.com",
  },
  {
    name: "Ashutosh",
    designation: "Mentor",
    image:  mentor,
    github: "www.github.com",
    linkedln: "www.linkedln.com",
  },
  {
    name: "Gopal",
    designation: "Mentor",
    image:  mentor,
    github: "www.github.com",
    linkedln: "www.linkedln.com",
  },
  {
    name: " Ashita",
    designation: "Mentor",
    image:  mentor,
    github: "www.github.com",
    linkedln: "www.linkedln.com",
  },
  {
    name: "Shivam",
    designation: "Mentor",
    image:  mentor,
    github: "www.github.com",
    linkedln: "www.linkedln.com",
  },
  {
    name: "Akshat",
    designation: "Mentor",
    image:  mentor,
    github: "www.github.com",
    linkedln: "www.linkedln.com",
  },
  {
    name: "Sunit",
    designation: "Mentor",
    image:  mentor,
    github: "www.github.com",
    linkedln: "www.linkedln.com",
  },
];
export {Mentors2021,Mentors2022,Mentors2023};
